---
title: "RealityCheckFor55"
output: html_document
lang: russian
```

```{r, include=FALSE}
rm(list=ls()) 

library(pander)

mylist <- readRDS("realityCheckData_percent_v1_09-07-2015 (Q=0.1).RDS") # читаем из файла что там есть 
realityCheckData<-mylist$data
```
Всего  было рассмотрено 55 тикеров со второго листа файла эмитенты КОТИРОВКИ.xlsx. 

Исследовались недельные цены закрытия, временной интервал, в рамках которого были данные по всем компаниям начинался 04.12.2011 и заканчивался 24.05.2015 - всего 181 неделя.

Оказалось, что у трех компаний с тикерами  "PHOR.RX.Equity", "IRAO.RX.Equity", "UNAC.RX.Equity" отсутствуют некоторые значения цен закрытия в указанном диапазоне,
поэтому в дальнейшем исследовалось 52 компании. Для них формировался вектор разностей доходностей размерности 74.

Всего было рассмотрено 12*12*9*4 = 5184  модели. Варьировались такие параметры, как время отбора (от 1 до 12 месяцев), время ожидания (от 0 до 8 недель), время инвестирования (от 1 до 12 месяцев), процент от общего количества в группе победителей и проигравших (50%, 30%, 20%, 10%)

Для проверки значимости лучшей модели использовалась процедура Bootstrap Reality Check с некоторыми параметрами.
Лучшей по средней доходности (0.05937230% в месяц) оказалась стратегия с параметрами        11 месяцев на отбор, 2 недели на ожидание, 4 месяца на инвестирование,
Портфели победителей и проигравших составляли 10% от общего количества компаний (5 победителей и 5 проигравших)
Bootstrap p-value =0.030, т.е. данная стратегия показала значимый результат на 5% уровне значимости.

В принципе наблюдался эффект увеличения средней доходности при уменьшении количества компаний в группах победителей и проигравших.

Топ 20 по средней доходности стратегий



```{r }
head( realityCheckData[order(- realityCheckData[,1]) ,-8],20)
```
